centreon:
  container_name: centreon-docker
  image: centreon-docker:v81
  restart: on-failure
  ports:
    - "80:80"
  privileged: true
  volumes:
    - /home/centreon/etc/centreon:/etc/centreon:rw
    - /home/centreon/etc/centreon-broker:/etc/centreon-broker:rw
    - /home/centreon/etc/centreon-engine:/etc/centreon-engine:rw
    - /home/centreon/etc/httpd/conf.d/:/etc/httpd/conf.d:rw
    - /home/centreon/etc/pki/:/etc/pki/:rw
    - /home/centreon/root/:/root/:rw
    - /home/centreon/usr/local/nagvis:/usr/local/nagvis:rw
    - /home/centreon/usr/local/src/:/usr/local/src/:rw
    - /home/centreon/usr/share/centreon:/usr/share/centreon:rw
    - /home/centreon/var/lib/centreon:/var/lib/centreon:rw
    - /home/centreon/var/log/centreon:/var/log/centreon:rw
    - /home/centreon/var/lib/centreon-broker:/var/lib/centreon-broker:rw
    - /home/centreon/var/log/centreon-broker:/var/log/centreon-broker:rw
    - /home/centreon/var/log/centreon-engine:/var/log/centreon-engine:rw
    - /home/centreon/var/log/httpd:/var/log/httpd:rw
    - /home/centreon/var/lib/mysql:/var/lib/mysql:rw
    - /home/centreon/var/lib/php:/var/lib/php:rw
